In [4]:
import cv2
import numpy as np
# load MASK RCNN

# Loading Mask RCNN
net = cv2.dnn.readNetFromTensorflow("dnn/frozen_inference_graph_coco.pb",
									"dnn/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt")

# Generate random colors
colors = np.random.randint(0, 255, (80, 3))

# Load the image

img = cv2.imread("people_walking.jpg")
height,width,_=img.shape

# Create black image
black_image = np.zeros((height, width, 3), np.uint8)
black_image[:] = (100, 100, 0)


# Detect objects

blob = cv2.dnn.blobFromImage(img, swapRB=True)#converting image into blobs
net.setInput(blob)
# boxes,masks = net.forward(["detection_out_final","detection_masks"])
boxes,masks = net.forward(["detection_out_final","detection_masks"])
detection_count = boxes.shape[2]
# print(detection_count)
# print(boxes)



# print all the objet in the image
for i in range(detection_count):
    box = boxes[0,0,i]
    print("box is", box)
    class_id = box[1]
    score = box[2]
    if score < 0.5:
        continue

    # For drawing bounding boxes
    # get box coordinate
    x = int(box[3] * width)
    y = int(box[4] * height)
    x2 = int(box[5] * width)
    y2 = int(box[6] * height)
    print(x,y,x2,y2)
    
    roi = black_image[y:y2,x:x2]
    roi_height,roi_width,_ = roi.shape
    
    # Get the mask
    mask = masks[i,int(class_id)]
    mask = cv2.resize(mask,(roi_width,roi_height))
    _,mask = cv2.threshold(mask,0.5,255,cv2.THRESH_BINARY)
    print(mask)
    
    # If rectangle maches with the image
    cv2.rectangle(img,(x,y),(x2,y2),(255,0,0),3)
    
    # Get mask coordinates
    contours, _ = cv2.findContours(np.array(mask,np.uint8),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    color = colors[int(class_id)]
    for cnt in contours:
        cv2.fillPoly(roi, [cnt], (int(color[0]), int(color[1]), int(color[2])))
                     
        
#     cv2.imshow("roi",roi)
#     cv2.waitKey(0)
    
    
# cv2.waitKey(0)
# cv2.destroyAllWindows()
                      
                      





# print("Boxes are\n",boxes)


cv2.imshow("image",img)
cv2.imshow("Black image",black_image)

cv2.waitKey(0)
cv2.destroyAllWindows()





box is [0.         0.         0.9982187  0.8037356  0.00272322 0.9404099
 0.40046728]
1205 2 1410 400
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
box is [0.         0.         0.99521834 0.21537775 0.01430565 0.37686986
 0.5429371 ]
323 14 565 542
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
box is [0.         0.         0.99474466 0.6183934  0.06559971 0.80920434
 0.689134  ]
927 65 1213 689
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
box is [0.         0.         0.9922333  0.43321738 0.0024215  0.49264643
 0.16813125]
649 2 738 168
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0